name: uncledsplayground
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.24164
title: "uncled's playground"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13181a'
    - '#f2dede'
    - '#326793'
    - '#a94442'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
