name: uncledsplayground
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.24164
title: "uncled's playground"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#255946'
    - '#a67968'
    - '#5ba67b'
    - '#d9ab91'
    - '#000000'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
