name: uncledsplayground
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24164
title: "uncled's playground"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cecfd1'
    - '#000000'
    - '#5b5b5b'
    - '#f72737'
    - '#781922'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
