name: uncledsplayground
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24164
title: "uncled's playground"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#cacaca'
    - '#555555'
    - '#949494'
  brandStrength: 0
  lightness: 0.896375872194767
  saturation: 0.7445163615047932
  rhythmicContrast: 0.7748432403896004
purpose: []
